garage/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('hardware.urls')),
    url(r'^sensors/', include('sensor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hardware/urls.py
from django.conf.urls import url
from . import views


app_name = 'hardware'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^device_on/(?P<device_id>[0-9]+)/$', views.device_on, name='device_on'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
]

sensor/urls.py
from django.conf.urls import url
from . import views


app_name = 'sensor'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update/temperature/$', views.update_temperature, name='update_temperature'),
    url(r'^check/motion/$', views.check_motion, name='check_motion'),
    url(r'^check/climate/$', views.check_climate, name='check_climate'),
    url(r'^temperature/json$', views.get_temp_inside_json, name='get_temp_inside_json'),
]

hardware/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.html import format_html
from image_cropping import ImageRatioField
from pin.models import Pin
from relay.models import Relay
from django.conf import settings


class Device(models.Model):
    name = models.CharField(null=False, max_length=100)
    relay = models.ForeignKey(Relay)
    is_active = models.BooleanField(default=False)
    image = models.ImageField(blank=True, upload_to='uploaded_images')
    cropped_image = ImageRatioField('image', '422x422')
    scheme_image = models.FileField(default='')

    def image_object(self):
        return format_html(
            '<img width=30 height=30 src="{}" />',
            self.image.url,
        )

    def scheme_image_object(self):
        return format_html(
            '<img width=30 height=30 src="{}" />',
            self.scheme_image.url,
        )

    image_object.admin_order_field = 'image'
    scheme_image_object.admin_order_field = 'scheme_image'

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(null=False, max_length=100)
    device = models.ManyToManyField(Device)

    def __str__(self):
        return self.name


class Schedule(models.Model):
    device = models.ForeignKey(Device)
    start_time = models.DateTimeField(auto_now=True)
    type = models.IntegerField(choices=settings.SCHEDULE_TYPE)

hardware/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

hardware/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import services
import sensor.services
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .forms import UserForm


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'hardware/login.html')
    else:
        devices = services.get_devices()
        dht22_sensors = sensor.services.get_sensors(2)

        return render(
            request,
            'hardware/index.html', {
                'devices': devices,
                'temperature': dht22_sensors,
            }
        )


def device_on(request, device_id):
    status = services.switch_device(int(device_id))
    if status:
        message = 'Turn off'
    else:
        message = 'Turn on'
    return JsonResponse({
        'success': status,
        'message': message
    })


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'hardware/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                devices = services.get_devices()
                return render(request, 'hardware/index.html', {'devices': devices})
            else:
                return render(request, 'hardware/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'hardware/login.html', {'error_message': 'Invalid login'})
    return render(request, 'hardware/login.html')

hardware/templates/hardware/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title>{% block title %}Garage{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'hardware/bootstrap.min.css' %}">
    <!--<link href="https://fonts.googleapis.com/css?family=Special+Elite" rel="stylesheet"> -->
    <!--<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">-->
    <link rel="stylesheet" type="text/css" href="{% static 'hardware/style.css' %}?e=2"/>
    <script src="{% static 'hardware/js/jquery.min.js' %}"></script>
    <script src="{% static 'hardware/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'hardware/js/main.js' %}?h=8"></script>
    {% block scripts %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'hardware:index' %}">Garage</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block devices_active %}{% endblock %}"><a href="{% url 'hardware:index' %}"><span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>&nbsp; Devices</a></li>
                <li class="{% block sensors_active %}{% endblock %}"><a href="{% url 'sensor:index' %}"><span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>&nbsp; Sensors</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'hardware:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'hardware:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

hardware/templates/hardware/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title>{% block title %}Garage{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'hardware/bootstrap.min.css' %}">
    <!--<link href="https://fonts.googleapis.com/css?family=Special+Elite" rel="stylesheet"> -->
    <!--<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">-->
    <link rel="stylesheet" type="text/css" href="{% static 'hardware/style.css' %}?e=2"/>
    <script src="{% static 'hardware/js/jquery.min.js' %}"></script>
    <script src="{% static 'hardware/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'hardware/js/main.js' %}?h=8"></script>
    {% block scripts %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'hardware:index' %}">Garage</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'hardware:login_user' %}">Log In</a></li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

hardware/templates/hardware/device_on.html
<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>

hardware/templates/hardware/index.html
{% extends 'hardware/base.html' %}
{% block devices_active %}active{% endblock %}
{% block title %}Devices list{% endblock %}
{% block body %}
<div class="films-container container-fluid">
    <div class="row">
        {% if temperature %}
            {% for t in temperature %}
                <div class="col-sm-4"><h4>{{ t.name }}</h4>{{ t.result }}</div>
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
            </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-12">
            <img src="http://garage.kuzmich.xyz/cam/" />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h3>Devices</h3>
        </div>
        {% if devices %}
            {% for device in devices %}
                <div class="col-sm-4 col-lg-3 col-xs-6">
                    <div class="thumbnail">
                        {% if device.image %}
                            {% load cropping %}
                            <img src="{% cropped_thumbnail device "cropped_image" %}" class="img-responsive">
                        {% endif %}
                        <div class="caption">
                            <h3>{{ device.name }}</h3>
                            <h4>Relay #{{ device.relay.number }}</h4>
                            <!-- Turn on/off -->
                            <a href="{% url 'hardware:device_on' device.id %}" class="btn btn-primary {% if device.is_active %}active{% endif %} ajax-link" role="button">Turn {% if device.is_active %}off{% else %}on{% endif %}</a>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
            </div>
        {% endif %}
    </div>

</div>
{% endblock %}

hardware/templates/hardware/login.html
{% extends 'hardware/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'hardware:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
        </div>
    </div>

</div>

{% endblock %}